apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multi-tier-deployment
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 4001
      targetPort: 4001
