apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: multi-tier-deployment
spec: 
  replicas: 2
  selector:
   matchLabels:
    app: backend
  template:
   metadata:
      labels:
        app: backend
   spec:
      containers:
      - name: backend
        image: hxrshal/multi-tier-backend:v6
        ports:
          - containerPort: 4001
        env:
          - name: REDIS_HOST
            value: "10.108.183.55"
          - name: REDIS_PORT
            value: "6379"
          - name: PORT
            value: "4001"
       

  