apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: multi-tier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hxrshal/multi-tier-frontend:v1
          ports:
            - containerPort: 80

